Manajemen Tags:
  Lokasi UI: >-
    - Sidebar > Flows > [Tab] Tags
  Referensi YAML Utama: >-
    - `appConfig.sidebar.menu[title=Flows].main.tabs[title=Tags]`
  Contoh Implementasi Tagging dalam Flow: >-
   - `04_flow_design.yml` -> `FlowLogic_Actions:TindakanActionAddTagFlow` (Cara penggunaan)
   - `booking_lapangan_example.yml` (Daftar tag untuk kasus booking)
   - `booking_lapangan_example.yml` (Otomatisasi tag via AI Parameters)

Manajemen Custom Fields:
  Lokasi UI: >-
    - Sidebar > Flows > [Tab] Custom Fields
  Referensi YAML Utama: >-
   - `appConfig.sidebar.menu[title=Flows].main.tabs[title=Custom Fields]`
  Penjelasan Perbedaan Custom Field vs Account Field: >-
   - `01_platform_basics.yml` -> `ContactManagement_Data:CustomFieldVsAccountFieldDataDinamisStatis`
  Contoh Implementasi Custom Fields: >-
    - `booking_lapangan_example.yml`

Manajemen AI Triggers:
  Lokasi UI (untuk membuat/mengelola): >-
    - Sidebar > Flows > [Tab] Ai Triggers
  Referensi YAML Utama: >-
    - `appConfig.sidebar.menu[title=Flows].main.tabs[title=Ai Triggers]`
  Panduan Pembuatan & Konfigurasi: >-
   - `02_ai_configuration.yml` -> `AIConfiguration_Triggers:AITriggersOtomatisasiResponsAlurKerja`
   - `04_flow_design.yml` -> `FlowTriggers_AutomatedExecution:MenjalankanFlowAITriggersBerdasarkanDeteksiNiatIntentPelanggan`
  Contoh Implementasi AI Triggers: >-
  - `booking_lapangan_example.yml`

Manajemen AI Parameters (Automation Rules):
  Lokasi UI: >-
    - Sidebar > Flows > [Tab] Ai Parameters
  Referensi YAML Utama: >-
    - `appConfig.sidebar.menu[title=Flows].main.tabs[title=Ai Parameters]`
  Panduan Penggunaan: >-
   -  `04_flow_design.yml` -> `FlowTriggers_AutomatedExecution:MenjalankanFlowSecaraOtomatisTriggersParametersParameterPemicu`
  Contoh Implementasi: >-
   - `booking_lapangan_example.yml`

Flow Editor & Komponennya:
  Akses: >-
   - `Sidebar > Flows > [Tab] Flows > [klik flow atau tombol add]`
  Referensi YAML Utama (Struktur Editor & Node): >-
   - `appConfig.sidebar.menu[title=Flows].main.tabs[title=Flows].flowEditorPage`
  Dasar Flow Builder: >-
   - `04_flow_design.yml` -> `FlowDesign_Core:DasarDasarFlowBuilderDragDrop`
  Penggunaan Variabel Sistem (seperti `{{last_input}}`): >-
   - `04_flow_design.yml` -> `FlowDesign_Core:VariabelSistemSepertiLast_inputPesan`
  Daftar Lengkap Variabel Sistem: >-
   - `02_ai_configuration.yml` -> `SystemVariables_Reference:DaftarLengkapSystemFieldsVariabelSistemPekerjaai`
  Contoh Flow Lengkap: >-
   - `booking_lapangan_example.yml` (setelah direstrukturisasi dengan benar)
   - `04_flow_design.yml` -> `UseCase_Examples_Detailed_Walkthroughs`

Integrasi Channel (WhatsApp, Instagram, dll.):
  Lokasi UI: >-
    - Sidebar > Connected Platforms
  Referensi YAML Utama: >-
   - `appConfig.sidebar.menu[title=Connected Platforms].mainRef: SettingsConnectedPlatforms`
  Panduan Detail per Channel: >-
   - `03_channel_integration.yml` (misalnya, `ChannelIntegration_Setup:MenghubungkanBotAIWhatsAppWhatsAppBusinessAPI`)

Tools (QR Code, E-commerce, Broadcast, dll.):
  Lokasi UI: >-
    - Sidebar > Tools
  Referensi YAML Utama: >-
   - `appConfig.sidebar.menu[title=Tools]`
  Panduan E-commerce (Import CSV): >-
   - `05_tools_extensions.yml` -> `Ecommerce_ProductFeatures:MenambahProdukFiturEcommerceMelaluiImporFileCSV`
  Panduan Broadcast: >-
   - `05_tools_extensions.yml` -> `Broadcast_MassMessaging`
  Panduan QR Code Generator: >-
   - `05_tools_extensions.yml` -> `PlatformTools_Utilities:PemanfaatanToolQRCodeGeneratorImageGenerationEditor`

Pengaturan Akun & Pengguna:
  Ganti Nama Akun: >-
   - `01_platform_basics.yml` -> `AccountManagement_Settings:MenggantiNamaAkunPekerjaAIAnda`
  Tambah Admin/Agen: >-
   - `01_platform_basics.yml` -> `AccountManagement_Settings:MenambahkanPenggunaAgenAdminAkunMengaturIzinAkses`
  Development Mode: >-
   - `01_platform_basics.yml` -> `AccountManagement_Settings:DevelopmentModePengujianBotTerisolasi`
